# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for all projects
      run: dotnet restore src/PDNDClientAssertionGenerator.sln

    - name: Build all projects
      run: dotnet build src/PDNDClientAssertionGenerator.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test src/PDNDClientAssertionGenerator.Tests/PDNDClientAssertionGenerator.Tests.csproj --no-build --verbosity normal
      continue-on-error: true # Optional: allows workflow to continue even if tests fail, but mark the job as failed
